Section "Device"
    Identifier "VirtualBox Graphics"
    Driver "vboxvideo"
    Option "DynamicResize" "true"
    Option "AccelMethod" "sna"
EndSection

Section "Screen"
    Identifier "Screen0"
    Device "VirtualBox Graphics"
    DefaultDepth 24
EndSection
