# Generated by Django 5.1 on 2026-05-28 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_kelasorder_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserKelasAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kelas_id', models.IntegerField()),
                ('kelas_nama', models.CharField(max_length=200)),
                ('order_id', models.CharField(max_length=50)),
                ('access_granted', models.BooleanField(default=True)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kelas_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'kelas_id')},
            },
        ),
    ]
